<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'app.cache' => 'get1',
  'app.flash' => 'get2',
  'app.view' => 'get3',
  'email.view' => 'get4',
  'sms.view' => 'get5',
  'app.audit' => 'get6',
  'app.logger' => 'get7',
  'sql.logger' => 'get8',
  'app.csrf' => 'get9',
  'html.purifier.config' => 'get10',
  'html.purifier' => 'get11',
  'debug.stack' => 'get12',
  'debug.sql.logger' => 'get13',
  'debug.timer' => 'get14',
  'app.security' => 'get15',
  'user.profile' => 'get16',
  'app.session' => 'get17',
  'mime.types' => 'get18',
  'app.language' => 'get19',
  'PHPMaker2024\\demo2024\\PermissionMiddleware' => 'get20',
  'PHPMaker2024\\demo2024\\ApiPermissionMiddleware' => 'get21',
  'PHPMaker2024\\demo2024\\JwtMiddleware' => 'get22',
  'FastRoute\\RouteParser\\Std' => 'get23',
  'Illuminate\\Encryption\\Encrypter' => 'get24',
  'cars' => 'get25',
  'categories' => 'get26',
  'customers' => 'get27',
  'employees' => 'get28',
  'orderdetails' => 'get29',
  'orders' => 'get30',
  'products' => 'get31',
  'shippers' => 'get32',
  'suppliers' => 'get33',
  'models' => 'get34',
  'trademarks' => 'get35',
  'userlevelpermissions' => 'get36',
  'userlevels' => 'get37',
  'order_details_extended' => 'get38',
  'orders2' => 'get39',
  'cars2' => 'get40',
  'home' => 'get41',
  'news' => 'get42',
  'order_details_extended_2' => 'get43',
  'sales_by_category_for_20142' => 'get44',
  'Quarterly_Orders_By_Product' => 'get45',
  'quarterly_orders_by_product' => 'get46',
  'Sales_By_Customer' => 'get47',
  'sales_by_customer' => 'get48',
  'Sales_By_Customer_Compact' => 'get49',
  'sales_by_customer_compact' => 'get50',
  'Alphabetical_List_of_Products' => 'get51',
  'alphabetical_list_of_products' => 'get52',
  'Products_By_Category' => 'get53',
  'products_by_category' => 'get54',
  'Sales_by_Category_for_2014' => 'get55',
  'sales_by_category_for_2014' => 'get56',
  'Sales_By_Year' => 'get57',
  'sales_by_year' => 'get58',
  'Sales_By_Order' => 'get59',
  'sales_by_order' => 'get60',
  'Sales_By_Customer_2' => 'get61',
  'sales_by_customer_2' => 'get62',
  'Dashboard1' => 'get63',
  'dashboard1' => 'get64',
  'orders_by_product2' => 'get65',
  'Gantt' => 'get66',
  'gantt' => 'get67',
  'calendar' => 'get68',
  'Calendar1' => 'get69',
  'calendar1' => 'get70',
  'join_premium' => 'get71',
  'audittrail' => 'get72',
  'konfirmasi_pembayaran' => 'get73',
  'usertable' => 'get74',
  'connection.DB' => 'get75',
  'entitymanager.DB' => 'get76',
  'connection.demo2' => 'get77',
  'entitymanager.demo2' => 'get78',
);

    protected function get1()
    {
        $object = new Slim\HttpCache\CacheProvider();
        return $object;
    }

    protected function get2()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Slim\Flash\Messages(), 'app.flash');
    }

    protected function get3()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Slim\Views\PhpRenderer($GLOBALS["RELATIVE_PATH"] . "views/"), 'app.view');
    }

    protected function get4()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Slim\Views\PhpRenderer($GLOBALS["RELATIVE_PATH"] . "lang/"), 'email.view');
    }

    protected function get5()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Slim\Views\PhpRenderer($GLOBALS["RELATIVE_PATH"] . "lang/"), 'sms.view');
    }

    protected function get6()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => (new \Monolog\Logger("audit"))->pushHandler(new \PHPMaker2024\demo2024\AuditTrailHandler($GLOBALS["RELATIVE_PATH"] . "log/audit.log")), 'app.audit');
    }

    protected function get7()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => (new \Monolog\Logger("log"))->pushHandler(new \Monolog\Handler\RotatingFileHandler($GLOBALS["RELATIVE_PATH"] . "log/log.log")), 'app.logger');
    }

    protected function get8()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $loggers = [];
        if (\PHPMaker2024\demo2024\Config("DEBUG")) {
            $loggers[] = $c->get("debug.stack");
        }
        return (count($loggers) > 0) ? new \Doctrine\DBAL\Logging\LoggerChain($loggers) : null;
    }, 'sql.logger');
    }

    protected function get9()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Slim\Csrf\Guard($GLOBALS["ResponseFactory"], \PHPMaker2024\demo2024\Config("CSRF_PREFIX")), 'app.csrf');
    }

    protected function get10()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => \HTMLPurifier_Config::createDefault(), 'html.purifier.config');
    }

    protected function get11()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \HTMLPurifier($c->get("html.purifier.config")), 'html.purifier');
    }

    protected function get12()
    {
        $object = new Doctrine\DBAL\Logging\DebugStack();
        return $object;
    }

    protected function get13()
    {
        $object = new PHPMaker2024\demo2024\DebugSqlLogger();
        return $object;
    }

    protected function get14()
    {
        $object = new PHPMaker2024\demo2024\Timer(true);
        return $object;
    }

    protected function get15()
    {
        $object = new PHPMaker2024\demo2024\AdvancedSecurity();
        return $object;
    }

    protected function get16()
    {
        $object = new PHPMaker2024\demo2024\UserProfile('');
        return $object;
    }

    protected function get17()
    {
        $object = new PHPMaker2024\demo2024\HttpSession();
        return $object;
    }

    protected function get18()
    {
        $object = new Symfony\Component\Mime\MimeTypes([
        ]);
        return $object;
    }

    protected function get19()
    {
        $object = new PHPMaker2024\demo2024\Language();
        return $object;
    }

    protected function get20()
    {
        $object = new PHPMaker2024\demo2024\PermissionMiddleware();
        return $object;
    }

    protected function get21()
    {
        $object = new PHPMaker2024\demo2024\ApiPermissionMiddleware();
        return $object;
    }

    protected function get22()
    {
        $object = new PHPMaker2024\demo2024\JwtMiddleware();
        return $object;
    }

    protected function get23()
    {
        $object = new FastRoute\RouteParser\Std();
        return $object;
    }

    protected function get24()
    {
        return $this->resolveFactory(static fn(\Psr\Container\ContainerInterface $c) => new \Illuminate\Encryption\Encrypter(\PHPMaker2024\demo2024\AesEncryptionKey(base64_decode(\PHPMaker2024\demo2024\Config("AES_ENCRYPTION_KEY"))), \PHPMaker2024\demo2024\Config("AES_ENCRYPTION_CIPHER")), 'Illuminate\\Encryption\\Encrypter');
    }

    protected function get25()
    {
        $object = new PHPMaker2024\demo2024\Cars();
        return $object;
    }

    protected function get26()
    {
        $object = new PHPMaker2024\demo2024\Categories();
        return $object;
    }

    protected function get27()
    {
        $object = new PHPMaker2024\demo2024\Customers();
        return $object;
    }

    protected function get28()
    {
        $object = new PHPMaker2024\demo2024\Employees();
        return $object;
    }

    protected function get29()
    {
        $object = new PHPMaker2024\demo2024\Orderdetails();
        return $object;
    }

    protected function get30()
    {
        $object = new PHPMaker2024\demo2024\Orders();
        return $object;
    }

    protected function get31()
    {
        $object = new PHPMaker2024\demo2024\Products();
        return $object;
    }

    protected function get32()
    {
        $object = new PHPMaker2024\demo2024\Shippers();
        return $object;
    }

    protected function get33()
    {
        $object = new PHPMaker2024\demo2024\Suppliers();
        return $object;
    }

    protected function get34()
    {
        $object = new PHPMaker2024\demo2024\Models();
        return $object;
    }

    protected function get35()
    {
        $object = new PHPMaker2024\demo2024\Trademarks();
        return $object;
    }

    protected function get36()
    {
        $object = new PHPMaker2024\demo2024\Userlevelpermissions();
        return $object;
    }

    protected function get37()
    {
        $object = new PHPMaker2024\demo2024\Userlevels();
        return $object;
    }

    protected function get38()
    {
        $object = new PHPMaker2024\demo2024\OrderDetailsExtended();
        return $object;
    }

    protected function get39()
    {
        $object = new PHPMaker2024\demo2024\Orders2();
        return $object;
    }

    protected function get40()
    {
        $object = new PHPMaker2024\demo2024\Cars2();
        return $object;
    }

    protected function get41()
    {
        $object = new PHPMaker2024\demo2024\Home();
        return $object;
    }

    protected function get42()
    {
        $object = new PHPMaker2024\demo2024\News();
        return $object;
    }

    protected function get43()
    {
        $object = new PHPMaker2024\demo2024\OrderDetailsExtended2();
        return $object;
    }

    protected function get44()
    {
        $object = new PHPMaker2024\demo2024\SalesByCategoryFor20142();
        return $object;
    }

    protected function get45()
    {
        $object = new PHPMaker2024\demo2024\QuarterlyOrdersByProduct();
        return $object;
    }

    protected function get46()
    {
        $object = new PHPMaker2024\demo2024\QuarterlyOrdersByProduct();
        return $object;
    }

    protected function get47()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomer();
        return $object;
    }

    protected function get48()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomer();
        return $object;
    }

    protected function get49()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomerCompact();
        return $object;
    }

    protected function get50()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomerCompact();
        return $object;
    }

    protected function get51()
    {
        $object = new PHPMaker2024\demo2024\AlphabeticalListOfProducts();
        return $object;
    }

    protected function get52()
    {
        $object = new PHPMaker2024\demo2024\AlphabeticalListOfProducts();
        return $object;
    }

    protected function get53()
    {
        $object = new PHPMaker2024\demo2024\ProductsByCategory();
        return $object;
    }

    protected function get54()
    {
        $object = new PHPMaker2024\demo2024\ProductsByCategory();
        return $object;
    }

    protected function get55()
    {
        $object = new PHPMaker2024\demo2024\SalesByCategoryFor2014();
        return $object;
    }

    protected function get56()
    {
        $object = new PHPMaker2024\demo2024\SalesByCategoryFor2014();
        return $object;
    }

    protected function get57()
    {
        $object = new PHPMaker2024\demo2024\SalesByYear();
        return $object;
    }

    protected function get58()
    {
        $object = new PHPMaker2024\demo2024\SalesByYear();
        return $object;
    }

    protected function get59()
    {
        $object = new PHPMaker2024\demo2024\SalesByOrder();
        return $object;
    }

    protected function get60()
    {
        $object = new PHPMaker2024\demo2024\SalesByOrder();
        return $object;
    }

    protected function get61()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomer2();
        return $object;
    }

    protected function get62()
    {
        $object = new PHPMaker2024\demo2024\SalesByCustomer2();
        return $object;
    }

    protected function get63()
    {
        $object = new PHPMaker2024\demo2024\Dashboard1();
        return $object;
    }

    protected function get64()
    {
        $object = new PHPMaker2024\demo2024\Dashboard1();
        return $object;
    }

    protected function get65()
    {
        $object = new PHPMaker2024\demo2024\OrdersByProduct2();
        return $object;
    }

    protected function get66()
    {
        $object = new PHPMaker2024\demo2024\Gantt();
        return $object;
    }

    protected function get67()
    {
        $object = new PHPMaker2024\demo2024\Gantt();
        return $object;
    }

    protected function get68()
    {
        $object = new PHPMaker2024\demo2024\Calendar();
        return $object;
    }

    protected function get69()
    {
        $object = new PHPMaker2024\demo2024\Calendar1();
        return $object;
    }

    protected function get70()
    {
        $object = new PHPMaker2024\demo2024\Calendar1();
        return $object;
    }

    protected function get71()
    {
        $object = new PHPMaker2024\demo2024\JoinPremium();
        return $object;
    }

    protected function get72()
    {
        $object = new PHPMaker2024\demo2024\Audittrail();
        return $object;
    }

    protected function get73()
    {
        $object = new PHPMaker2024\demo2024\KonfirmasiPembayaran();
        return $object;
    }

    protected function get74()
    {
        return $this->delegateContainer->get('employees');
    }

    protected function get75()
    {
        return $this->resolveFactory(static function (string $dbid) {
        return \PHPMaker2024\demo2024\ConnectDb(\PHPMaker2024\demo2024\Db($dbid));
    }, 'connection.DB', [
            'dbid' => 'DB',
        ]);
    }

    protected function get76()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c, string $dbid) {
        $cache = \PHPMaker2024\demo2024\IsDevelopment()
            ? \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(new \Symfony\Component\Cache\Adapter\ArrayAdapter())
            : \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(new \Symfony\Component\Cache\Adapter\FilesystemAdapter(directory: \PHPMaker2024\demo2024\Config("DOCTRINE.CACHE_DIR")));
        $config = \Doctrine\ORM\Tools\Setup::createAttributeMetadataConfiguration(
            \PHPMaker2024\demo2024\Config("DOCTRINE.METADATA_DIRS"),
            \PHPMaker2024\demo2024\IsDevelopment(),
            null,
            $cache
        );
        $conn = $c->get("connection." . $dbid);
        return new \Doctrine\ORM\EntityManager($conn, $config);
    }, 'entitymanager.DB', [
            'dbid' => 'DB',
        ]);
    }

    protected function get77()
    {
        return $this->resolveFactory(static function (string $dbid) {
        return \PHPMaker2024\demo2024\ConnectDb(\PHPMaker2024\demo2024\Db($dbid));
    }, 'connection.demo2', [
            'dbid' => 'demo2',
        ]);
    }

    protected function get78()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c, string $dbid) {
        $cache = \PHPMaker2024\demo2024\IsDevelopment()
            ? \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(new \Symfony\Component\Cache\Adapter\ArrayAdapter())
            : \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(new \Symfony\Component\Cache\Adapter\FilesystemAdapter(directory: \PHPMaker2024\demo2024\Config("DOCTRINE.CACHE_DIR")));
        $config = \Doctrine\ORM\Tools\Setup::createAttributeMetadataConfiguration(
            \PHPMaker2024\demo2024\Config("DOCTRINE.METADATA_DIRS"),
            \PHPMaker2024\demo2024\IsDevelopment(),
            null,
            $cache
        );
        $conn = $c->get("connection." . $dbid);
        return new \Doctrine\ORM\EntityManager($conn, $config);
    }, 'entitymanager.demo2', [
            'dbid' => 'demo2',
        ]);
    }

}
